import re
import urllib.request
from pathlib import Path

SOURCE = 'https://raw.githubusercontent.com/Womsxd/MyAdBlockRules/refs/heads/master/p2pcdnblock.txt'
REGEX_MAP = {
    r'/^(.+)-p2p-pull\.(video|live)-voip\.com$/': ['?*-p2p-pull.video-voip.com', '?*-p2p-pull.live-voip.com'],
    r'/^(.+)-p2p\.pull\.yximgs\.com$/': ['?*-p2p.pull.yximgs.com'],
    r'/^(.+)-p2p-(.+)\.pull\.yximgs\.com$/': ['?*-p2p-?*.pull.yximgs.com'],
}
KNOWN_OMISSION = r'/trk-([0-9\-]+)\.douyucdn\.cn/'

def convert(source):
    rules, unknown = [], []
    for raw in source.splitlines():
        line = raw.strip()
        if not line or line.startswith(('!', '#')):
            continue
        if line in REGEX_MAP:
            rules.extend('host-wildcard, ' + mask + ', reject' for mask in REGEX_MAP[line])
        elif line == KNOWN_OMISSION:
            continue
        elif re.fullmatch(r'\|\|[A-Za-z0-9.*_-]+\^', line):
            mask = line[2:-1].lower()
            if '*' in mask:
                rules.append('host-wildcard, ' + mask + ', reject')
                if not mask.startswith('*'):
                    rules.append('host-wildcard, *.' + mask + ', reject')
            else:
                rules.append('host-suffix, ' + mask + ', reject')
        else:
            unknown.append(line)
    if unknown:
        raise ValueError('New unsupported upstream syntax; existing published file kept:\n' + '\n'.join(unknown))
    if not rules:
        raise ValueError('No valid rules; existing published file kept')
    header = ['# Womsxd PCDN converted for Quantumult X', '# Upstream: ' + SOURCE,
              '# Generated by convert.py; enable daily updates in QX.',
              '# Known omission: numeric/hyphen trk regex has no exact QX wildcard equivalent.']
    return '\n'.join(header + list(dict.fromkeys(rules))) + '\n'

if __name__ == '__main__':
    request = urllib.request.Request(SOURCE, headers={'User-Agent': 'PCDN-QX-Converter'})
    with urllib.request.urlopen(request, timeout=60) as response:
        source = response.read().decode('utf-8-sig')
    result = convert(source)
    Path('Womsxd-PCDN-QuantumultX.list').write_text(result, encoding='utf-8')
    print('Converted', sum(not line.startswith('#') for line in result.splitlines()), 'rules')
